server:
    address: 192.168.1.100
---
spring:
    profiles: development
server:
    address: 127.0.0.1
    port: 8090
system:
    name: hello
    age:  11
---
spring:
    profiles: production
server:
    address: 192.168.1.120
---
spring.profiles.active: development

